name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./brewhouse-manager
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements/test.txt
          python -m pip install -r ./requirements/requirements.txt
      - name: Run Pytest
        working-directory: ./brewhouse-manager
        run: |
          pytest
